// samples/config.js  — AUTO-GENERATED by scripts/generate-sample-config.js
// Do not edit this file manually. Run: node scripts/generate-sample-config.js
// Only browser-safe values are written here. Secret keys are never included.
//
// This file is listed in .gitignore and must NOT be committed.
// Generate it locally by copying .env.example → .env, filling in your values,
// then running:  node scripts/generate-sample-config.js

window.AJJ_SAMPLE_CONFIG = {
  // Stripe Payment Link — Stripe-hosted checkout page (Tab A).
  stripePaymentLink: "REPLACE_WITH_YOUR_STRIPE_PAYMENT_LINK",

  // Stripe publishable key — safe to expose in the browser (Tab B / Card form).
  // pk_live_ keys charge real money; use pk_test_ keys for development.
  stripePublishableKey: "REPLACE_WITH_YOUR_STRIPE_PUBLISHABLE_KEY",
};
