// samples/config.js  — AUTO-GENERATED by scripts/generate-sample-config.js
// Do not edit this file manually. Run: node scripts/generate-sample-config.js
// Only browser-safe values are written here. Secret keys are never included.

window.AJJ_SAMPLE_CONFIG = {
  // Stripe Payment Link — Stripe-hosted checkout page (Tab A).
  stripePaymentLink: "https://buy.stripe.com/00gaGRbct9JU2Nq6oo",

  // Stripe publishable key — safe to expose in the browser (Tab B / Card form).
  // pk_live_ keys charge real money; use pk_test_ keys for development.
  stripePublishableKey: "pk_live_51NbJDeIa1rnxdXb79SmODPPFPMPRU7r3xWVvbBohl5hRFSO3ijkggsgUBkbdFWVGKHI8WkODTYfmilsWElucVsIb00ndHM6QD7",
};
